apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: graph-docs
  template:
    metadata:
      labels:
        name: graph-docs
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: app
        image: graph-docs
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            port: http
